// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from './routes/[...docs].tsx'
import * as $1 from './routes/_404.tsx'
import * as $2 from './routes/_app.tsx'
import * as $3 from './routes/index.tsx'
import * as $4 from './routes/next.ts'
import * as $5 from './routes/prev.ts'
import * as $6 from './routes/rand.ts'
import * as $$0 from './islands/Counter.tsx'

const manifest = {
  routes: {
    './routes/[...docs].tsx': $0,
    './routes/_404.tsx': $1,
    './routes/_app.tsx': $2,
    './routes/index.tsx': $3,
    './routes/next.ts': $4,
    './routes/prev.ts': $5,
    './routes/rand.ts': $6,
  },
  islands: {
    './islands/Counter.tsx': $$0,
  },
  baseUrl: import.meta.url,
}

export default manifest
